FORMAT: 1A
HOST: http://www.example.com

# Subway Info
Subway Info API is a service that provides information about various subway systems in a standard, easily accessible format.

# Group Subways
Various subway systems

## Subways Collection [/]
### List all Subway systems [GET]
+ Response 200 (application/json)

        
            [
              {
                "_id": "52eefc3eb7332070cf8ac574",
                "name": "Washington Metro",
                "href": "/dc-metro",
                "authority": {
                  "name": "Washington Metropolitan Area Transit Authority",
                  "url": "http://wmata.com"
                },
                "location": {
                  "city": "Washington",
                  "subdivision": {
                    "name": "District of Columbia",
                    "code": "US-DC"
                  },
                  "country": {
                    "name": "United States of America",
                    "code": "US"
                  }
                }
              }
            ]

## Subway [/{subwayId}]
A single subway system object with all its details

+ Parameters
    + subwayId (required, text, `dc-metro`) ... Textual `id` of the subway system to perform action with.

### Retrieve a Subway [GET]
+ Response 200 (application/json)

    + Body

            {
                _id: "52eefc3eb7332070cf8ac574",
                name: "Washington Metro",
                href: "/dc-metro",
                authority: {
                    name: "Washington Metropolitan Area Transit Authority",
                    url: "http://wmata.com"
                },
                location: {
                    city: "Washington",
                    subdivision: {
                        name: "District of Columbia",
                        code: "US-DC"
                    },
                    country: {
                        name: "United States of America",
                        code: "US"
                    }
                }
            }

# Group Stations
Subway stations for a given subway system

## Station Collection [/{subwayId}/stations]

+ Parameters
    + subwayId (required, text, `dc-metro`) ... Textual `id` of the subway system to perform action with.

### Retrieve a list of stations [GET]

+ Response 200 (application/json)

        
            [
              {
                "_id": "52eefc3eb7332070cf8ac574",
                "name": "Washington Metro",
                "href": "/dc-metro",
                "authority": {
                  "name": "Washington Metropolitan Area Transit Authority",
                  "url": "http://wmata.com"
                },
                "location": {
                  "city": "Washington",
                  "subdivision": {
                    "name": "District of Columbia",
                    "code": "US-DC"
                  },
                  "country": {
                    "name": "United States of America",
                    "code": "US"
                  }
                }
              }
            ]